# Generated by Django 3.0.11 on 2022-08-09 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False)),
                ('deviceRoom', models.CharField(blank=True, max_length=16)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('clientAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=24)),
                ('status', models.BooleanField(default=True)),
                ('deviceRoom', models.CharField(blank=True, max_length=16)),
                ('start_session', models.DateTimeField(auto_now_add=True)),
                ('stop_session', models.DateTimeField(auto_now_add=True)),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.ClientDevice')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDeviceSegmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField(unique=True)),
                ('status', models.CharField(default='UNREGISTERED', max_length=14)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandaloneDeviceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu_chamber_a', models.IntegerField(default=0)),
                ('suhu_chamber_b', models.IntegerField(default=0)),
                ('suhu_output_pasien', models.IntegerField(default=0)),
                ('suhu_heater_plate', models.IntegerField(default=0)),
                ('arus_heater_plate', models.IntegerField(default=0)),
                ('arus_heater_wire', models.IntegerField(default=0)),
                ('date_record', models.DateTimeField(auto_now_add=True)),
                ('clientAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deviceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ClientDevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu_chamber_a', models.IntegerField(default=0)),
                ('suhu_chamber_b', models.IntegerField(default=0)),
                ('suhu_output_pasien', models.IntegerField(default=0)),
                ('suhu_heater_plate', models.IntegerField(default=0)),
                ('arus_heater_plate', models.IntegerField(default=0)),
                ('arus_heater_wire', models.IntegerField(default=0)),
                ('code', models.SmallIntegerField(default=0, null=True)),
                ('date_record', models.DateTimeField(auto_now_add=True)),
                ('clientAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deviceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ClientDevice')),
                ('sessionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.DeviceSession')),
            ],
        ),
    ]
